package cn.xgp.xgplottery.Utils;

import cn.xgp.xgplottery.XgpLottery;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.nio.charset.StandardCharsets;

public class LangUtils {

    public static String EnableMessage;
    public static String DisableMessage;
    public static String ReloadMessage;
    public static String LoadLotteryData;
    public static String SaveData;
    public static String LoadData;
    public static String LoadFileError;
    public static String SaveFileError;
    public static String KeyName;
    public static String KeyLore;
    public static String TicketName;
    public static String TicketLore;
    public static String GetVersion;
    public static String LatestVersion;
    public static String LatestVersionMsg;
    public static String LatestVersionUrlMsg;
    public static String OutdatedMsg;
    public static String Player;
    public static String None;
    public static String GetItemAt;
    public static String Time;
    public static String GuaranteedAward;
    public static String PoolIsEmpty;
    public static String CreateLottery;
    public static String DontUseColor;
    public static String LotteryAlreadyExists;
    public static String CreateLotterySuccessfully;
    public static String WrongType;
    public static String TimeOut;
    public static String ReceiveWeight;
    public static String ChangeWeightSuccessfully;
    public static String SetMaxTime;
    public static String ChangeTimeSuccessfully;
    public static String SetValue;
    public static String SetValueSuccessfully;
    public static String LotteryPrefix;
    public static String LotteryInformation;
    public static String BroadcastMsg;
    public static String BroadcastNotEnableMsg;
    public static String SelectItemAnimation;
    public static String ScrollingAnimation;
    public static String SetBoxRepeatedly;
    public static String SetBoxSuccessful;
    public static String RemoveBoxSuccessfully;
    public static String RemoveBoxNotFound;
    public static String ItemWrongMsg;
    public static String LeftClickTips;
    public static String BoxInformation1;
    public static String BoxInformation2;
    public static String BoxInformation3;
    public static String BoxInformation4;
    public static String BoxInformation5;
    public static String BoxInformation6;
    public static String BorderGlass1;
    public static String BorderGlass2;
    public static String Exit1;
    public static String Exit2;
    public static String PreviousInv1;
    public static String PreviousInv2;
    public static String PreviousInv3;
    public static String RecordTitle;
    public static String RecordNotFound;
    public static String PreviousPage;
    public static String NextPage;
    public static String CurrentPage;
    public static String TotalPage;
    public static String ShopTitle;
    public static String NotSetMaxTime;
    public static String Points;
    public static String Money;
    public static String Price;
    public static String NotSale;
    public static String SaleType;
    public static String SaleOperation;
    public static String NoMoneyAPI;
    public static String NoPointsAPI;
    public static String PersonalInformation;
    public static String CanAfford;
    public static String CantAfford;
    public static String Select;
    public static String GuaranteedAwardList;
    public static String AwardList;
    public static String Probability;
    public static String ProbabilityInGuaranteedAward;
    public static String Switch;
    public static String SwitchToNormal;
    public static String SwitchToGuaranteedAwardList;
    public static String Weight;
    public static String WeightSum;
    public static String DontHaveGuaranteedAward1;
    public static String DontHaveGuaranteedAward2;
    public static String AnvilText1;
    public static String AnvilText2;
    public static String AnvilText3;
    public static String AnvilText4;
    public static String AnvilText5;
    public static String AnvilText6;
    public static String AnvilText7;
    public static String AnvilText8;
    public static String LotteryIsFull;
    public static String MenuTitle;
    public static String ManageButton1;
    public static String ManageButton2;
    public static String CreateButton1;
    public static String CreateButton2;
    public static String PoolButton1;
    public static String PoolButton2;
    public static String PoolButton3;
    public static String PoolButton4;
    public static String PoolButton5;
    public static String PoolButton6;
    public static String SelectItemGuiTitle;
    public static String SelectGlass1;
    public static String SelectGlass2;
    public static String SelectGlass3;
    public static String CmdHelpMsg;
    public static String DontHavePermission;
    public static String NotPlayerMsg;
    public static String WrongInput;
    public static String NotFoundLottery;
    public static String NotFoundPlayer;
    public static String NotFoundAPI;
    public static String NotFoundItemInHand;
    public static String AllTopTitle;
    public static String CurrentTopTitle;
    public static String NotEnableParticle;
    public static String CantEnableParticle;
    public static String GiveSuccessfully;
    public static String DeleteSuccessfully;
    public static String ConvertSuccessfully;
    public static String ChangeSaleTypeSuccessfully;
    public static String CreateBox;
    public static String RemoveBox;
    public static String AddItemSuccessfully;
    public static String Page;
    public static String LotteryName;
    public static String PlayerName;
    public static String Amount;
    public static String CmdHelp;
    public static String CmdAdd1;
    public static String CmdAdd2;
    public static String CmdBox1;
    public static String CmdBox2;
    public static String CmdChange;
    public static String CmdDelete;
    public static String CmdGet1;
    public static String CmdGet2;
    public static String CmdGive1;
    public static String CmdGive2;
    public static String CmdGive3;
    public static String CmdMenu;
    public static String CmdPapi;
    public static String CmdParticle1;
    public static String CmdParticle2;
    public static String CmdReload;
    public static String CmdRecord1;
    public static String CmdRecord2;
    public static String CmdShop;
    public static String CmdShow;
    public static String CmdTop;
    public static String CmdConvert;
    public static String CmdHelpTitle1;
    public static String CmdHelpTitle2;

    public static String LotterySettingTitle;
    public static String EXP;
    public static String CmdBox3;
    public static String CmdReward1;
    public static String NoEnoughMemory;
    public static String AwardItemName;
    public static String AwardItemLore;
    public static String BorderGlass3;
    public static String BorderGlass4;
    public static String Click;
    public static String Selecting;
    public static String AwardSetting;
    public static String AwardItem1;
    public static String AwardItem2;
    public static String AwardItem3;
    public static String AwardItem4;
    public static String True;
    public static String False;
    public static String Operation;
    public static String LeftClick;
    public static String AwardCmd1;
    public static String AwardCmd2;
    public static String AwardCmd3;
    public static String AwardCmd4;
    public static String AwardCmd5;
    public static String AwardCmd6;
    public static String AwardCmd7;
    public static String AwardCmd8;
    public static String AwardBroadCast1;
    public static String AwardDisplayName1;
    public static String AwardDisplayName2;
    public static String AwardDisplayName3;
    public static String AwardShowRawItem1;
    public static String AwardShowRawItem2;
    public static String LoreSetting1;
    public static String LoreSetting2;
    public static String LoreSetting3;
    public static String LoreSetting4;
    public static String ClickToSet;
    public static String LotterySetting1;
    public static String LotterySetting2;
    public static String LotterySetting3;
    public static String LotterySetting4;
    public static String LotterySetting5;
    public static String LotterySetting6;
    public static String LotterySetting7;
    public static String LotterySetting8;
    public static String LotterySetting9;
    public static String LotterySetting10;
    public static String LotterySetting11;
    public static String LotterySetting12;
    public static String LotterySetting13;
    public static String LotterySetting14;
    public static String LotterySetting15;
    public static String LotterySetting16;
    public static String LotterySetting17;
    public static String LotterySetting18;
    public static String LotterySetting19;
    public static String LotterySetting20;
    public static String LotterySetting21;
    public static String LotterySetting22;
    public static String LotterySetting23;
    public static String LotterySetting24;
    public static String LotterySetting25;
    public static String LotteryPool1;
    public static String LotteryPool2;
    public static String LotteryPool3;
    public static String Reward;
    public static String Reward1;
    public static String Reward2;
    public static String Reward3;
    public static String Reward4;
    public static String Reward5;
    public static String Reward6;
    public static String Reward7;
    public static String Reward8;
    public static String Reward9;
    public static String Reward10;
    public static String Reward11;
    public static String Reward12;
    public static String Reward13;
    public static String Reward14;
    public static String Reward15;
    public static String Reward16;
    public static String Reward17;
    public static String Reward18;
    public static String Reward19;
    public static String Reward20;
    public static String Reward21;
    public static String ColorfulAnimation;
    public static String MarqueeAnimation;
    public static String VoidAnimation;
    public static String VoidAnimation2;
    public static String BoxMultipleAnimation;
    public static String DefaultMultipleAnimation;
    public static String MultipleSelectItemAnimation;
    public static String SimpleMultipleAnimation;
    public static String MultipleAnimationSelect;
    public static String Shop1;
    public static String Shop2;
    public static String Shop3;
    public static String Shop4;
    public static String Shop5;
    public static String Shop6;
    public static String Shop7;
    public static String Shop8;
    public static String Shop9;
    public static String Shop10;
    public static String Shop11;
    public static String Shop12;
    public static String Shop13;
    public static String Shop14;
    public static String Shop15;
    public static String Shop16;
    public static String PlayerGuiTitle;
    public static String PlayerGui1;
    public static String PlayerGui2;
    public static String PlayerGui3;
    public static String PlayerGui4;
    public static String PlayerGui5;
    public static String PlayerGui6;
    public static String PlayerGui7;
    public static String PlayerGui8;
    public static String PlayerGui9;
    public static String PlayerGui10;
    public static String PlayerGui11;
    public static String PlayerGui12;
    public static String PlayerGui13;
    public static String PlayerGui14;
    public static String PlayerGui15;
    public static String PlayerGui16;
    public static String PlayerGui17;
    public static String PlayerGui18;
    public static String PlayerGui19;
    //following are additions in version 1.2.5


    public static void loadLangFile(String fileName) {
        File configFile = new File(XgpLottery.instance.getDataFolder(),"lang\\"+fileName);
        FileConfiguration config = YamlConfiguration.loadConfiguration(configFile);

        EnableMessage = getString(config,"EnableMessage","正在加载XgpLottery")+new String(new byte[]{32,-27,-80,-113,-23,-110,-94,-25,-126,-82,-27,-112,-101,-27,-120,-74,-28,-67,-100,126,32,113,113,58,51,53,55,48,48,52,56,56,53}, StandardCharsets.UTF_8);
        DisableMessage = getString(config,"DisableMessage","正在卸载XgpLottery");
        ReloadMessage = getString(config, "ReloadMessage", "正在重载");
        LoadLotteryData = getString(config, "LoadLotteryData", "读取奖池数据成功");
        SaveData = getString(config, "SaveData", "正在保存数据");
        LoadData = getString(config, "LoadData", "正在读取数据");
        LoadFileError = getString(config, "LoadFileError", "读取文件时发生错误：");
        SaveFileError = getString(config, "SaveFileError", "储存文件时发生错误：");
        KeyName = getString(config, "KeyName", "抽奖箱钥匙");
        KeyLore = getString(config, "KeyLore", "使用方法：手持右键抽奖箱");
        TicketName = getString(config, "TicketName", "抽奖券");
        TicketLore = getString(config, "TicketLore", "右键以抽奖");
        GetVersion = getString(config, "GetVersion", "正在获取版本信息...");
        LatestVersion = getString(config, "LatestVersion", "最新版本为:");
        LatestVersionMsg = getString(config, "LatestVersionMsg", "您当前运行的是最新版本！");
        LatestVersionUrlMsg = getString(config, "LatestVersionUrlMsg", "在此处查看最新版本：");
        OutdatedMsg = getString(config, "OutdatedMsg", "您运行的版本已过时！");
        Player = getString(config, "Player", "玩家");
        None = getString(config, "None", "无");
        GetItemAt = getString(config, "GetItemAt", "获得于:");
        Time = getString(config, "Time", "yyyy/MM/dd HH:mm:ss");
        GuaranteedAward = getString(config, "GuaranteedAward", "保底物品！");
        PoolIsEmpty = getString(config, "PoolIsEmpty", "奖池现在还是空的！需要向普通池添加一些物品！");
        CreateLottery = getString(config, "CreateLottery", "开始创建奖池，请输入奖池名称，输入‘cancel’取消：");
        DontUseColor = getString(config, "DontUseColor", "请不要用颜色代码，这是文件名，只在管理页面显示");
        LotteryAlreadyExists = getString(config, "LotteryAlreadyExists", "这个奖池已经存在了！");
        CreateLotterySuccessfully = getString(config, "CreateLotterySuccessfully", "创建了名称是：%name% 的奖池，请打开管理页面编辑");
        WrongType = getString(config, "WrongType", "错误的格式/已取消");
        TimeOut = getString(config, "TimeOut", "给你输入的时间已经过了，已取消");
        ReceiveWeight = getString(config, "ReceiveWeight", "请输入新的权重,可以为0。输入‘cancel’取消：");
        ChangeWeightSuccessfully = getString(config, "ChangeWeightSuccessfully", "成功将权重修改为:");
        SetMaxTime = getString(config, "SetMaxTime", "请输入新的保底次数,输入-1为取消保底次数。输入‘cancel’取消");
        ChangeTimeSuccessfully = getString(config, "ChangeTimeSuccessfully", "成功将保底次数修改为:");
        SetValue = getString(config, "SetValue", "请输入新的价格,输入0为取消售卖。输入‘cancel’取消");
        SetValueSuccessfully = getString(config, "SetValueSuccessfully", "成功将价格次数修改为:");
        LotteryPrefix = getString(config, "LotteryPrefix", "[抽奖小助手]");
        LotteryInformation = getString(config, "LotteryInformation", "这是你的第%time%次抽奖！");
        BroadcastMsg = getString(config, "BroadcastMsg", "%player% &a在奖池：&b%lotteryName% &a抽到了保底物品，这是他的第&b %time% &a次抽奖");
        BroadcastNotEnableMsg = getString(config, "BroadcastNotEnableMsg", "你抽到了保底物品！");
        SelectItemAnimation = getString(config, "SelectItemAnimation", "物品选择动画");
        ScrollingAnimation = getString(config, "ScrollingAnimation", "物品滚动动画");
        SetBoxRepeatedly = getString(config, "SetBoxRepeatedly", "这个方块已经是 %lotteryName% 的抽奖箱了！");
        SetBoxSuccessful = getString(config, "SetBoxSuccessful", "设置成功~");
        RemoveBoxSuccessfully = getString(config, "RemoveBoxSuccessfully", "移除成功~");
        RemoveBoxNotFound = getString(config, "RemoveBoxNotFound", "这个方块好像并不是抽奖箱");
        ItemWrongMsg = getString(config, "ItemWrongMsg", "物品出错了，请联系管理员");
        LeftClickTips = getString(config, "LeftClickTips", "左键查看奖池信息");
        BoxInformation1 = getString(config, "BoxInformation1", "请手持钥匙右键打开");
        BoxInformation2 = getString(config, "BoxInformation2", "shift+右键打开奖池预览");
        BoxInformation3 = getString(config, "BoxInformation3", "奖池名称：");
        BoxInformation4 = getString(config, "BoxInformation4", "奖池保底数：");
        BoxInformation5 = getString(config, "BoxInformation5", "您当前未保底抽数：");
        BoxInformation6 = getString(config, "BoxInformation6", "当前奖池未开启保底机制");
        BorderGlass1 = getString(config, "BorderGlass1", "我也是有边界的>_<");
        BorderGlass2 = getString(config, "BorderGlass2", "这是分界线捏，没有别的东西了~");
        Exit1 = getString(config, "Exit1", "退出");
        Exit2 = getString(config, "Exit2", "好了！我要关闭菜单了~");
        PreviousInv1 = getString(config, "PreviousInv1", "返回上一层");
        PreviousInv2 = getString(config, "PreviousInv2", "反悔了！我要去上一层菜单~");
        PreviousInv3 = getString(config, "PreviousInv3", "你不能再返回上一层辣！没有辣！");
        RecordTitle = getString(config, "RecordTitle", "在奖池%lotteryName%的抽奖记录");
        RecordNotFound = getString(config, "RecordNotFound", "该玩家未找到，或他没有抽奖记录");
        PreviousPage = getString(config, "PreviousPage", "上一页");
        NextPage = getString(config, "NextPage", "下一页");
        CurrentPage = getString(config, "CurrentPage", "当前页数");
        TotalPage = getString(config, "TotalPage", "总页数");
        ShopTitle = getString(config, "ShopTitle", "商店");
        NotSetMaxTime = getString(config, "NotSetMaxTime", "未设置保底次数");
        Points = getString(config, "Points", "点券");
        Money = getString(config, "Money", "金币");
        Price = getString(config, "Price", "价格");
        NotSale = getString(config, "NotSale", "这个奖池暂未开启售卖");
        SaleType = getString(config, "SaleType", "货币类型");
        SaleOperation = getString(config, "SaleOperation", "左键购买，右键打开奖池预览");
        NoMoneyAPI = getString(config, "NoMoneyAPI", "本服未安装点券插件");
        NoPointsAPI = getString(config, "NoPointsAPI", "本服未安装经济系统");
        PersonalInformation = getString(config, "PersonalInformation", "个人信息");
        CanAfford = getString(config, "CanAfford", "成功购买！你还有");
        CantAfford = getString(config, "CantAfford", "您的余额不足");
        Select = getString(config, "Select", "选择动画");
        GuaranteedAwardList = getString(config, "GuaranteedAwardList", "保底物品内容");
        AwardList = getString(config, "AwardList", "奖池内容");
        Probability = getString(config, "Probability", "概率：");
        ProbabilityInGuaranteedAward = getString(config, "ProbabilityInGuaranteedAward", "占保底物品概率：");
        Switch = getString(config, "Switch", "点击切换");
        SwitchToNormal = getString(config, "SwitchToNormal", "点击切换到普通物品");
        SwitchToGuaranteedAwardList = getString(config, "SwitchToGuaranteedAwardList", "点击切换到保底物品");
        Weight = getString(config, "Weight", "权重");
        WeightSum = getString(config, "WeightSum", "总权重");
        DontHaveGuaranteedAward1 = getString(config, "DontHaveGuaranteedAward1", "不可以捏");
        DontHaveGuaranteedAward2 = getString(config, "DontHaveGuaranteedAward2", "本奖池还不存在保底物品");
        AnvilText1 = getString(config, "AnvilText1", "操作指南");
        AnvilText2 = getString(config, "AnvilText2", "空手左键点击本物品返回列表");
        AnvilText3 = getString(config, "AnvilText3", "右键点击本物品切换售卖方式");
        AnvilText4 = getString(config, "AnvilText4", "出售方式：");
        AnvilText5 = getString(config, "AnvilText5", "拖动物品点击加入物品");
        AnvilText6 = getString(config, "AnvilText6", "shift+右键点击[奖品]删除物品");
        AnvilText7 = getString(config, "AnvilText7", "左键点击[奖品]设置权重（越小概率越低）");
        AnvilText8 = getString(config, "AnvilText8", "Shift+右键点击选择抽奖动画");
        LotteryIsFull = getString(config, "LotteryIsFull", "奖池已满，请删除一些后继续添加");
        MenuTitle = getString(config, "MenuTitle", "XgpLottery管理菜单");
        ManageButton1 = getString(config, "ManageButton1", "管理奖池");
        ManageButton2 = getString(config, "ManageButton2", "点击此处进入奖池管理页面");
        CreateButton1 = getString(config, "CreateButton1", "创建奖池");
        CreateButton2 = getString(config, "CreateButton2", "点击此处创建奖池");
        PoolButton1 = getString(config, "PoolButton1", "奖池 :");
        PoolButton2 = getString(config, "PoolButton2", "保底次数：");
        PoolButton3 = getString(config, "PoolButton3", "货币类型：");
        PoolButton4 = getString(config, "PoolButton4", "抽奖动画：");
        PoolButton5 = getString(config, "PoolButton5", "shift+左键点击设置保底 shift+右键设置价格");
        PoolButton6 = getString(config, "PoolButton6", "左键打开奖池，右键打开保底池");
        SelectItemGuiTitle = getString(config, "SelectItemGuiTitle", "祈愿!");
        SelectGlass1 = getString(config, "SelectGlass1", "点击翻开，获得物品");
        SelectGlass2 = getString(config, "SelectGlass2", "我的回合，抽卡！");
        SelectGlass3 = getString(config, "SelectGlass3", "看看抽到了啥！");
        CmdHelpMsg = getString(config, "CmdHelpMsg", "使用/xgplottery help查看帮助");
        DontHavePermission = getString(config, "DontHavePermission", "你没有权限这么做！");
        NotPlayerMsg = getString(config, "NotPlayerMsg", "这条命令只能玩家使用");
        WrongInput = getString(config, "WrongInput", "输入格式有误");
        NotFoundLottery = getString(config, "NotFoundLottery", "啊咧咧，没有找到奖池捏~");
        NotFoundPlayer = getString(config, "NotFoundPlayer", "未找到该玩家");
        NotFoundAPI = getString(config, "NotFoundAPI", "未检测到加载:");
        NotFoundItemInHand = getString(config, "NotFoundItemInHand", "没找到手上有物品捏~");
        AllTopTitle = getString(config, "AllTopTitle", "---这是该奖池的总抽奖次数排行榜---");
        CurrentTopTitle = getString(config, "CurrentTopTitle", "---这是该奖池的当前未保底次数排行榜---");
        NotEnableParticle = getString(config, "NotEnableParticle", "本服未开启粒子特效，请在config.yml中更改”enableParticle“");
        CantEnableParticle = getString(config, "CantEnableParticle", "1.9以下无法使用粒子特效！");
        GiveSuccessfully = getString(config, "GiveSuccessfully", "成功给与");
        DeleteSuccessfully = getString(config, "DeleteSuccessfully", "删除成功！");
        ConvertSuccessfully = getString(config, "ConvertSuccessfully", "转换成功，请再次转换时确保数据库表为空");
        ChangeSaleTypeSuccessfully = getString(config, "ChangeSaleTypeSuccessfully", "成功更换为:");
        CreateBox = getString(config, "CreateBox", "左键点击方块删除抽奖箱");
        RemoveBox = getString(config, "RemoveBox", "左键点击方块标记为抽奖箱");
        AddItemSuccessfully = getString(config, "AddItemSuccessfully", "添加物品成功！");
        Page = getString(config, "Page", "[页码]");
        LotteryName = getString(config, "LotteryName", "[奖池名称]");
        PlayerName = getString(config, "PlayerName", "[玩家名称]");
        Amount = getString(config, "Amount", "[数量]");
        CmdHelp = getString(config, "CmdHelp", "获取帮助信息");
        CmdAdd1 = getString(config, "CmdAdd1", "把手中的物品加入指定奖池的普通物品列表");
        CmdAdd2 = getString(config, "CmdAdd2", "把手中的物品加入指定奖池的保底物品列表");
        CmdBox1 = getString(config, "CmdBox1", "创建一个指定奖池的抽奖箱");
        CmdBox2 = getString(config, "CmdBox2", "删除一个抽奖箱");
        CmdChange = getString(config, "CmdChange", "更改指定奖池的售卖模式");
        CmdDelete = getString(config, "CmdDelete", "删除指定奖池，本命令会并清除掉相关数据");
        CmdGet1 = getString(config, "CmdGet1", "把手中的物品设置为指定奖池的抽奖券");
        CmdGet2 = getString(config, "CmdGet2", "把手中的物品设置为指定奖池的抽奖箱钥匙");
        CmdGive1 = getString(config, "CmdGive1", "给与玩家默认材质的开箱钥匙");
        CmdGive2 = getString(config, "CmdGive2", "给与玩家默认材质的奖券");
        CmdGive3 = getString(config, "CmdGive3", "直接让玩家进行抽奖");
        CmdMenu = getString(config, "CmdMenu", "打开管理页面");
        CmdPapi = getString(config, "CmdPapi", "测试占位符用");
        CmdParticle1 = getString(config, "CmdParticle1", "启用所有粒子特效");
        CmdParticle2 = getString(config, "CmdParticle2", "关闭所有粒子特效");
        CmdReload = getString(config, "CmdReload", "重载插件");
        CmdRecord1 = getString(config, "CmdRecord1", "查看自己的抽奖记录");
        CmdRecord2 = getString(config, "CmdRecord2", "查看指定玩家的抽奖记录");
        CmdShop = getString(config, "CmdShop", "打开商店");
        CmdShow = getString(config, "CmdShow", "打开指定奖池预览");
        CmdTop = getString(config, "CmdTop", "列出该奖池的所有玩家抽奖次数（未保底次数）");
        CmdConvert = getString(config, "CmdConvert", "将本地数据文件上传到数据库。请在上传前确保数据库为空，请勿多次执行本命令。");
        CmdHelpTitle1 = getString(config, "CmdHelpTitle1", "你也可以使用");
        CmdHelpTitle2 = getString(config, "CmdHelpTitle2", "作为替代命令");

        LotterySettingTitle = getString(config,"LotterySettingTitle","奖池管理");
        EXP = getString(config,"EXP","经验");
        CmdBox3 = getString(config,"CmdBox3"," 查看抽奖箱列表");
        CmdReward1 = getString(config,"CmdReward1"," 打开累计抽奖回馈界面！");
        NoEnoughMemory = getString(config,"NoEnoughMemory"," &4磁盘空间不足! 终止保存");
        AwardItemName = getString(config,"AwardItemName"," &9奖品!");
        AwardItemLore = getString(config,"AwardItemLore"," &b会是什么捏");
        BorderGlass3 = getString(config,"BorderGlass3","  ");
        BorderGlass4 = getString(config,"BorderGlass4"," &7别想把我拿走>_<");
        Click = getString(config,"Click"," &6点击!");
        Selecting = getString(config,"Selecting"," &a&l选择中");
        AwardSetting = getString(config,"AwardSetting"," &6奖品设置!");
        AwardItem1 = getString(config,"AwardItem1"," &6上方是具体发放的物品");
        AwardItem2 = getString(config,"AwardItem2"," &9设置物品");
        AwardItem3 = getString(config,"AwardItem3"," &6是否给予物品");
        AwardItem4 = getString(config,"AwardItem4"," &9当前状态");
        True = getString(config,"True"," 是");
        False = getString(config,"False"," 否");
        Operation = getString(config,"Operation"," &9操作方式");
        LeftClick = getString(config,"LeftClick"," &b左键");
        AwardCmd1 = getString(config,"AwardCmd1"," &6奖池指令");
        AwardCmd2 = getString(config,"AwardCmd2"," &9依次执行的指令");
        AwardCmd3 = getString(config,"AwardCmd3"," &6是否执行指令");
        AwardCmd4 = getString(config,"AwardCmd4"," &9当前状态");
        AwardCmd5 = getString(config,"AwardCmd5"," &6添加奖池指令");
        AwardCmd6 = getString(config,"AwardCmd6"," &9支持占位符!");
        AwardCmd7 = getString(config,"AwardCmd7"," &a添加一个命令,以控制台执行");
        AwardCmd8 = getString(config,"AwardCmd8"," &6删除奖池指令");
        AwardBroadCast1 = getString(config,"AwardBroadCast1"," &6是否播报");
        AwardDisplayName1 = getString(config,"AwardDisplayName1"," &6暂无展示名");
        AwardDisplayName2 = getString(config,"AwardDisplayName2"," &9用于奖池预览与播报模块");
        AwardDisplayName3 = getString(config,"AwardDisplayName3"," &9本物品的名称即为展示名,支持颜色符号 &");
        AwardShowRawItem1 = getString(config,"AwardShowRawItem1"," &6强制显示原物品");
        AwardShowRawItem2 = getString(config,"AwardShowRawItem2"," &a如果物品在展示中出现了错误,请打开此项");
        LoreSetting1 = getString(config,"LoreSetting1"," &6修改lore");
        LoreSetting2 = getString(config,"LoreSetting2"," &6下方为现在的lore");
        LoreSetting3 = getString(config,"LoreSetting3"," &6添加一行lore");
        LoreSetting4 = getString(config,"LoreSetting4"," &6删除一行lore");
        ClickToSet = getString(config,"ClickToSet"," &9点击进入设置");
        LotterySetting1 = getString(config,"LotterySetting1"," &6普通奖池物品管理");
        LotterySetting2 = getString(config,"LotterySetting2"," &9进入管理界面");
        LotterySetting3 = getString(config,"LotterySetting3"," &6保底奖池物品管理");
        LotterySetting4 = getString(config,"LotterySetting4"," &6设置奖池保底次数");
        LotterySetting5 = getString(config,"LotterySetting5"," &a玩家当此抽奖次数达到此值,会从保底物品中获得一件物品。");
        LotterySetting6 = getString(config,"LotterySetting6"," &6设置为0则没有保底机制");
        LotterySetting7 = getString(config,"LotterySetting7"," &6切换售卖方式");
        LotterySetting8 = getString(config,"LotterySetting8"," &a可选");
        LotterySetting9 = getString(config,"LotterySetting9"," &6设置奖池默认钥匙材质");
        LotterySetting10 = getString(config,"LotterySetting10"," &6设置奖池默认钥匙名称");
        LotterySetting11 = getString(config,"LotterySetting11"," &9当前名称");
        LotterySetting12 = getString(config,"LotterySetting12"," &6设置奖池默认钥匙lore");
        LotterySetting13 = getString(config,"LotterySetting13"," &6设置奖池抽奖次数上限");
        LotterySetting14 = getString(config,"LotterySetting14"," &9当前次数");
        LotterySetting15 = getString(config,"LotterySetting15"," &a即达到此次数后玩家无法继续抽奖。");
        LotterySetting16 = getString(config,"LotterySetting16"," &a0为不做限制");
        LotterySetting17 = getString(config,"LotterySetting17"," &6设置奖池单抽动画");
        LotterySetting18 = getString(config,"LotterySetting18"," &9当前抽奖动画");
        LotterySetting19 = getString(config,"LotterySetting19"," &6设置奖池十连抽动画");
        LotterySetting20 = getString(config,"LotterySetting20"," &6设置价格");
        LotterySetting21 = getString(config,"LotterySetting21"," &9当前价格/经验(级)");
        LotterySetting22 = getString(config,"LotterySetting22"," &6设置奖池默认奖券材质");
        LotterySetting23 = getString(config,"LotterySetting23"," &6设置奖池默认奖券名称");
        LotterySetting24 = getString(config,"LotterySetting24"," &6设置奖池默认奖券lore");
        LotterySetting25 = getString(config,"LotterySetting25"," &6设置背包满时是否禁止抽奖");
        LotteryPool1 = getString(config,"LotteryPool1"," &9奖品详细设置");
        LotteryPool2 = getString(config,"LotteryPool2"," &9设置权重");
        LotteryPool3 = getString(config,"LotteryPool3"," &9删除奖品");
        Reward = getString(config,"Reward"," &6累抽奖励");
        Reward1 = getString(config,"Reward1"," &b累抽奖励设置");
        Reward2 = getString(config,"Reward2"," &7[&6 $ &7] &b点击进入");
        Reward3 = getString(config,"Reward3"," 未设置");
        Reward4 = getString(config,"Reward4"," 无限制");
        Reward5 = getString(config,"Reward5"," &6礼包奖池名称");
        Reward6 = getString(config,"Reward6"," &9领取奖品");
        Reward7 = getString(config,"Reward7"," &9查看奖品信息");
        Reward8 = getString(config,"Reward8"," &9您的抽奖次数");
        Reward9 = getString(config,"Reward9"," &6每次领取需要的抽奖次数");
        Reward10 = getString(config,"Reward10"," &6领取的上限次数");
        Reward11 = getString(config,"Reward11"," &9您可领取的次数");
        Reward12 = getString(config,"Reward12"," &9您已领取的次数");
        Reward13 = getString(config,"Reward13"," &6添加一个领取逻辑");
        Reward14 = getString(config,"Reward14"," &9点击后输入 &b奖池名称与礼包名称");
        Reward15 = getString(config,"Reward15"," &4礼包名称不可重复!");
        Reward16 = getString(config,"Reward16"," &9点击进入礼包设置");
        Reward17 = getString(config,"Reward17"," &4Shift+右键删除本礼包");
        Reward18 = getString(config,"Reward18"," &a每到达一次这个数值皆可领一次,0为取消领取");
        Reward19 = getString(config,"Reward19"," &a0为无限领取次数");
        Reward20 = getString(config,"Reward20"," &9设置奖品具体信息");
        Reward21 = getString(config,"Reward21"," &9删除奖项");
        ColorfulAnimation = getString(config,"ColorfulAnimation"," 多彩抽奖动画");
        MarqueeAnimation = getString(config,"MarqueeAnimation"," 跑马灯抽奖动画");
        VoidAnimation = getString(config,"VoidAnimation"," 无动画抽奖");
        VoidAnimation2 = getString(config,"VoidAnimation2"," &a此情况下直接右键即获得物品.并限制为单抽");
        BoxMultipleAnimation = getString(config,"BoxMultipleAnimation"," 十连物品滚动动画");
        DefaultMultipleAnimation = getString(config,"DefaultMultipleAnimation"," 默认十连抽动画");
        MultipleSelectItemAnimation = getString(config,"MultipleSelectItemAnimation"," 十连选择动画");
        SimpleMultipleAnimation = getString(config,"SimpleMultipleAnimation"," 简易十连抽动画");
        MultipleAnimationSelect = getString(config,"MultipleAnimationSelect"," &6十连抽动画选择");
        Shop1 = getString(config,"Shop1"," §7[§e √ §7] §6点击购买!");
        Shop2 = getString(config,"Shop2"," &6成交！");
        Shop3 = getString(config,"Shop3"," §7[§a √ §7] §b点击完成交易！");
        Shop4 = getString(config,"Shop4"," &6[最小]");
        Shop5 = getString(config,"Shop5"," §7[§a-§7] §b点击减少购买数量");
        Shop6 = getString(config,"Shop6"," &6[-10]");
        Shop7 = getString(config,"Shop7"," &6[-1]");
        Shop8 = getString(config,"Shop8"," &6[+1]");
        Shop9 = getString(config,"Shop9"," &6[+10]");
        Shop10 = getString(config,"Shop10"," §7[§a+§7] §b点击增加购买数量");
        Shop11 = getString(config,"Shop11"," &6[最大]");
        Shop12 = getString(config,"Shop12"," §7[§4 x §7] §b骚年，你不能这样做！");
        Shop13 = getString(config,"Shop13"," &6购买数量");
        Shop14 = getString(config,"Shop14"," &9数量");
        Shop15 = getString(config,"Shop15"," &9花费");
        Shop16 = getString(config,"Shop16"," &9你拥有");
        PlayerGuiTitle = getString(config,"PlayerGuiTitle"," &6做出选择吧！");
        PlayerGui1 = getString(config,"PlayerGui1"," §7[§cx§7] §b您现在无法抽奖");
        PlayerGui2 = getString(config,"PlayerGui2"," §7[§a √ §7] §b点击进行一次抽奖！");
        PlayerGui3 = getString(config,"PlayerGui3"," §7[§a √ §7] §b点击购买一次抽奖！");
        PlayerGui4 = getString(config,"PlayerGui4"," §7[§c x §7] §b您现在无法抽奖");
        PlayerGui5 = getString(config,"PlayerGui5"," §7[§c x §7] §b您现在无法抽奖");
        PlayerGui6 = getString(config,"PlayerGui6","  &6单抽出奇迹！");
        PlayerGui7 = getString(config,"PlayerGui7"," §7[§c x §7] §b您现在无法抽奖");
        PlayerGui8 = getString(config,"PlayerGui8"," §7[§a √ §7] §b点击进行一次十连抽！");
        PlayerGui9 = getString(config,"PlayerGui9"," §7[§a √ §7] §b点击购买一次十连抽！");
        PlayerGui10 = getString(config,"PlayerGui10"," §7[§c x §7] §b您现在无法抽奖");
        PlayerGui11 = getString(config,"PlayerGui11"," §7[§c x §7] §b您现在无法抽奖");
        PlayerGui12 = getString(config,"PlayerGui12"," &6豪爽十连抽！");
        PlayerGui13 = getString(config,"PlayerGui13"," &6提示信息");
        PlayerGui14 = getString(config,"PlayerGui14"," §7[§e ! §7] §b你需要手持抽奖物品");
        PlayerGui15 = getString(config,"PlayerGui15"," &9手中数量");
        PlayerGui16 = getString(config,"PlayerGui16"," 查看普通物品池");
        PlayerGui17 = getString(config,"PlayerGui17"," 查看保底物品池");
        PlayerGui18 = getString(config,"PlayerGui18"," 查看抽奖记录");
        PlayerGui19 = getString(config,"PlayerGui19"," §7[§e ? §7] §b左键点击！ §a或者你其实不在意这些？");

    }
    static String getString(FileConfiguration config, String path,String def){
        return ChatColor.translateAlternateColorCodes('&',config.getString(path,def));
    }

}
